// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmMrSt978jZ8epcvlLvqDE1v4N7x8pONw',
    appId: '1:1077293288373:web:1eac44459b2ac56948a7fc',
    messagingSenderId: '1077293288373',
    projectId: 'elixir-a7849',
    authDomain: 'elixir-a7849.firebaseapp.com',
    storageBucket: 'elixir-a7849.firebasestorage.app',
    measurementId: 'G-N37L36XDN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLscUgakW3JaEcBs6Y315dUTbC6YMzqM4',
    appId: '1:1077293288373:android:91a988dbe55eb6af48a7fc',
    messagingSenderId: '1077293288373',
    projectId: 'elixir-a7849',
    storageBucket: 'elixir-a7849.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARfF4HZFJ-cQuxJJ6--20f9zGgrw0yNAI',
    appId: '1:1077293288373:ios:f7421d7e1fd672b548a7fc',
    messagingSenderId: '1077293288373',
    projectId: 'elixir-a7849',
    storageBucket: 'elixir-a7849.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARfF4HZFJ-cQuxJJ6--20f9zGgrw0yNAI',
    appId: '1:1077293288373:ios:f7421d7e1fd672b548a7fc',
    messagingSenderId: '1077293288373',
    projectId: 'elixir-a7849',
    storageBucket: 'elixir-a7849.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmMrSt978jZ8epcvlLvqDE1v4N7x8pONw',
    appId: '1:1077293288373:web:179b27362cfca9ef48a7fc',
    messagingSenderId: '1077293288373',
    projectId: 'elixir-a7849',
    authDomain: 'elixir-a7849.firebaseapp.com',
    storageBucket: 'elixir-a7849.firebasestorage.app',
    measurementId: 'G-8XL1FQTYP5',
  );
}
