// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClHM2Xj1fgGhtDgX8xdOKSycyvH7uc2l4',
    appId: '1:427636974612:web:9913061bfdc02d0028f301',
    messagingSenderId: '427636974612',
    projectId: 'elixir-ca085',
    authDomain: 'elixir-ca085.firebaseapp.com',
    storageBucket: 'elixir-ca085.firebasestorage.app',
    measurementId: 'G-M5T3C4JFXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmf7kDPMy8P9EL2u-knCv0zFeLaUXn8Lw',
    appId: '1:427636974612:android:93b17961a030f43428f301',
    messagingSenderId: '427636974612',
    projectId: 'elixir-ca085',
    storageBucket: 'elixir-ca085.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0bneHrPDAtBoZVligCd6M2alN6mI_8SE',
    appId: '1:427636974612:ios:3b411c40e2d12ddb28f301',
    messagingSenderId: '427636974612',
    projectId: 'elixir-ca085',
    storageBucket: 'elixir-ca085.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0bneHrPDAtBoZVligCd6M2alN6mI_8SE',
    appId: '1:427636974612:ios:3b411c40e2d12ddb28f301',
    messagingSenderId: '427636974612',
    projectId: 'elixir-ca085',
    storageBucket: 'elixir-ca085.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClHM2Xj1fgGhtDgX8xdOKSycyvH7uc2l4',
    appId: '1:427636974612:web:c939d435404ef54328f301',
    messagingSenderId: '427636974612',
    projectId: 'elixir-ca085',
    authDomain: 'elixir-ca085.firebaseapp.com',
    storageBucket: 'elixir-ca085.firebasestorage.app',
    measurementId: 'G-HQHJJMXL4Z',
  );
}
